#!/bin/bash

cd ../annotations

./build distclean
./build programs

cd bin
./createhtml
./ziphtml

cd ../../sf

yodl2html index || exit 1
unzip ../annotations/zip/cplusplus.html.zip

scp -r index.html annotations \
        fbb,cppannotations@web.sourceforge.net:htdocs/

rm -rf annotations

cd ../annotations

./build distclean







