#!/bin/bash

_project_=cppannotations
_product_=annotations

echo -n "Need to (re)create ${_project_}'s wip files for gh-pages [y/n] ? "
read yesno

if [ "$yesno" == "y" ] ; then
    git co master

    cd ${_product_}                 # check
    ./build man
    ./build docs
    ./build zips

    ./build github
    ./build distclean
    cd ..    
    git co gh-pages

    cp -r ../wip/changelog.txt ../wip/c++-annotations-man.html .
    rm -r cppannotations
    unzip ../wip/zips/cplusplus.html.zip

    cp ../wip/zips/*.zip ../../cppannotations-zip/
fi

echo
echo -n "Check index.yo: version and last 5 releases [y/n] ? "
read yesno

if [ "$yesno" == "y" ] ; then
    emacs index.yo
fi

yodl2html index.yo || exit 1

echo "Running 'git st': no untracked files or ignorable files should be shown"
git st

echo 

echo -n "ci change to index.html etc., push the result and co master [y/n] ? "
read yesno

if [ "$yesno" == "y" ] ; then
    RELEASE=`head -n1 ../wip/version.yo | 
                sed 's/SUBST(DOCVERSION)(\(.*\))/\1/'`

    msgDefault="gh-pages for release ${RELEASE}"

    echo -n "Enter the ci message [default: $msgDefault]"

    read msg;

    [ "$msg" == "" ] && msg=$msgDefault
    git ci -am "$msg"
    git push
    git co master

    echo zip archives at ~/git/cppannotations-zip: 
    echo git push and git tag in that directory to upload    
fi







