#!/bin/bash

cd ..
./build distclean
./build programs

cd bin
./createhtml
./ziphtml

cd ../sourceforge
yodl2html index || exit 1
unzip ../zip/cplusplus.html.zip

scp -r index.html c++annotations \
        fbb,cppannotations@web.sourceforge.net:htdocs/

rm -rf c++annotations

cd ..
./build distclean
