#!/bin/bash

# echo "
#     Run in .. 'build docs' and 'build zips' and in bin: createhtml and
#     ziphtml to create the  html zip in zip. Run 'sourcetar l' to
#     create an archive. 
# "

# ssh -t fbb,cppannotations@shell.sourceforge.net create


cd ..
sourcetar l
build docs
build zips
cd sourceforge
emacs  release.notes

yodl2html index || exit 1
 
scp index.html ../tmp/docs/zips/cplusplus.html.zip fbb,cppannotations@shell.sourceforge.net:/home/groups/c/cp/cppannotations/htdocs

echo "
Log in at sourceforge using 
    ssh fbb,cppannotations@shell.sourceforge.net
or, to create a shell:
    ssh -t fbb,cppannotations@shell.sourceforge.net create 
and 
    cd /home/groups/c/cp/cppannotations/htdocs
There do:
    rm -r cppannotations
    unzip cplusplus.html.zip
    rm cplusplus.html.zip

Then upload release notes, ../../c++-annotations_8.1.0*.tar.gz, ../tmp/docs/* 
to sourceforge
"


