#!/bin/sh

echo "
    Run 'build docs' and 'build zips' and in bin: createhtml and
    ziphtml to create the  html zip in zip. Run 'sourcetar l' to
    create an archive. 
"

# ssh -t fbb,cppannotations@shell.sourceforge.net create

yodl2html index || exit 1

scp index.html ../zip/cplusplus.html.zip fbb,cppannotations@shell.sourceforge.net:/home/groups/c/cp/cppannotations/htdocs

