#!/bin/sh

echo "
    Run 'build docs' to create the docs in the zip subdirectory and run
    sourcetar l to create an archive and put it also in the ./zip dir.
    Before uploading make sure all files in a new release contain the
    release nr.  E.g., cplusplus.8.0.0.html.zip rather than
    cplusplus.html.zip
"

yodl2html index || exit 1

scp index.html annotations.jpg fbb,cppannotations@web.sourceforge.net:htdocs/
