#!/bin/bash

echo '<!DOCTYPE html><html><head>
<meta charset="UTF-8">
<title>C++ Annotations Contents</title>
<link rev="made" href="mailto:Frank B. Brokken: f.b.brokken@rug.nl">
</head>
<body>
<script>
function load(next)
{
    opener.info.location=next;
    return (false);
}
</script>
'

grep 'd[dlt]>' cplusplus.html |
sed '
    s/"\(cplusplus[0-9]\+\.html#l[0-9]\+\)"/"\1" onclick="return load('"'"'\1'"'"')"/
    s/<p>//g
' 


echo '</body>
</html>
'
