#!/bin/bash

# not used anymore. previously called from ~/icmake/docs

# sed '
#     s/"/\\"/g
#     s/!/$!$/g
#     s/</\$<\$/g
#     s/>/\$>\$/g
# ' cplusplus${1}.ind > cplusplus.ind.out
# 
# mv cplusplus.ind.out cplusplus${1}.ind
